import type { BriefResult, Company } from '@/lib/types';

const pipelineCompanies = [
  ['cmp_kestrelhealth', 'Kestrel Health AI', 'Diligence', 'Clinical operations'],
  ['cmp_atlasgrid', 'AtlasGrid AI', 'Partner review', 'Industrial computer vision'],
  ['cmp_cedarrobotics', 'Cedar Robotics', 'First meeting', 'Warehouse robotics'],
  ['cmp_prismlegal', 'Prism Legal AI', 'Diligence', 'Legal software'],
  ['cmp_sagebio', 'SageBio Systems', 'Screening', 'Life science software'],
  ['cmp_quantaledger', 'QuantaLedger', 'Diligence', 'Finance operations'],
  ['cmp_relayworks', 'RelayWorks AI', 'First meeting', 'Field service software'],
  ['cmp_northstarsecurity', 'Northstar Security AI', 'Sourced', 'Security operations'],
];

export const fallbackCompanies: Company[] = [
  {
    id: 'cmp_vectorforge',
    name: 'VectorForge AI',
    aliases: ['VectorForge', 'Vector Forge'],
    relationshipStatus: 'portfolio',
    pipelineStage: null,
    companyStage: 'Series A',
    sector: 'AI infrastructure',
    description:
      'VectorForge reduces the cost and delay of model inference for enterprise software teams.',
    owner: 'RC',
    lastReviewDate: '2026-07-25T15:00:00Z',
    updatedAt: '2026-08-20T15:05:00Z',
    sourceCount: 10,
    latestSourceDate: '2026-08-20T15:05:00Z',
    sourceCategories: ['crm', 'meeting', 'slack', 'news'],
  },
  {
    id: 'cmp_lumenops',
    name: 'LumenOps AI',
    aliases: ['LumenOps'],
    relationshipStatus: 'portfolio',
    pipelineStage: null,
    companyStage: 'Seed',
    sector: 'Customer support software',
    description:
      'LumenOps reviews support conversations and identifies service risks.',
    owner: 'RC',
    lastReviewDate: '2026-08-10T17:00:00Z',
    updatedAt: '2026-08-16T14:35:00Z',
    sourceCount: 9,
    latestSourceDate: '2026-08-16T14:35:00Z',
    sourceCategories: ['crm', 'meeting', 'slack', 'news'],
  },
  ...pipelineCompanies.map(([id, name, pipelineStage, sector], index) => ({
    id,
    name,
    aliases: [],
    relationshipStatus: 'pipeline' as const,
    pipelineStage,
    companyStage: index < 4 ? 'Seed' : 'Pre-seed',
    sector,
    description: `Review the available evidence for ${name}.`,
    owner: index % 3 === 1 ? 'Maya Chen' : 'RC',
    lastReviewDate: null,
    updatedAt: '2026-08-25T12:00:00Z',
    sourceCount: index < 4 ? 5 : 3,
    latestSourceDate: '2026-08-25T12:00:00Z',
    sourceCategories: ['crm', 'slack', 'news'],
  })),
];

export const fallbackBrief: BriefResult = {
  company: fallbackCompanies[0],
  generatedAt: '2026-08-31T14:02:00Z',
  durationMs: 1840,
  mode: 'evidence-fallback',
  inputQuery: 'Current company state, changes, risks, and open questions',
  currentState: [
    {
      id: 'current-1',
      text: 'Recognized annual recurring revenue is 3.4 million USD. An earlier record states 3.8 million USD because it includes contracts that had not started.',
      sourceIds: ['meeting-001', 'crm-activity-002', 'slack-001'],
      sourceDate: '2026-07-29T13:05:00Z',
      state: 'conflict',
      kind: 'fact',
    },
    {
      id: 'current-2',
      text: 'Monthly burn is 420000 USD. Reported runway is approximately 14 months.',
      sourceIds: ['meeting-001', 'crm-activity-001'],
      sourceDate: '2026-07-25T15:00:00Z',
      state: 'confirmed',
      kind: 'fact',
    },
    {
      id: 'current-3',
      text: 'The company plans to start a Series B process in January 2027.',
      sourceIds: ['slack-017', 'meeting-001'],
      sourceDate: '2026-08-20T15:05:00Z',
      state: 'confirmed',
      kind: 'fact',
    },
  ],
  changes: [
    {
      id: 'change-1',
      text: 'Northbank expanded from one production workload to four workloads. Contract value increased by 180000 USD.',
      sourceIds: ['crm-activity-003'],
      sourceDate: '2026-08-06T16:00:00Z',
      state: 'confirmed',
      kind: 'fact',
    },
    {
      id: 'change-2',
      text: 'The company opened four infrastructure engineering roles.',
      sourceIds: ['slack-003'],
      sourceDate: '2026-08-15T10:15:00Z',
      state: 'confirmed',
      kind: 'fact',
    },
  ],
  risks: [
    {
      id: 'risk-1',
      text: 'The company has not confirmed the gross margin effect of the Northbank expansion.',
      sourceIds: ['meeting-001', 'slack-002'],
      sourceDate: '2026-08-07T14:20:00Z',
      state: 'missing',
      kind: 'analysis',
    },
    {
      id: 'risk-2',
      text: 'New hiring can increase burn before the planned funding process.',
      sourceIds: ['slack-003', 'slack-017'],
      sourceDate: '2026-08-20T15:05:00Z',
      state: 'unverified',
      kind: 'analysis',
    },
  ],
  openQuestions: [
    {
      id: 'open-1',
      text: 'What is recognized annual recurring revenue after the August close?',
      sourceIds: ['meeting-001'],
      sourceDate: '2026-07-25T15:00:00Z',
      state: 'missing',
      kind: 'question',
    },
    {
      id: 'open-2',
      text: 'What is the gross margin effect of the Northbank expansion?',
      sourceIds: ['crm-activity-003'],
      sourceDate: '2026-08-06T16:00:00Z',
      state: 'missing',
      kind: 'question',
    },
  ],
  suggestedQuestions: [
    {
      id: 'suggested-1',
      text: 'Which two customer expansions must close before the Series B process starts?',
      sourceIds: ['meeting-001', 'slack-017'],
      sourceDate: '2026-08-20T15:05:00Z',
      state: 'confirmed',
      kind: 'question',
    },
    {
      id: 'suggested-2',
      text: 'How will new infrastructure hiring change monthly burn and runway?',
      sourceIds: ['slack-003'],
      sourceDate: '2026-08-15T10:15:00Z',
      state: 'confirmed',
      kind: 'question',
    },
  ],
  sources: [
    {
      id: 'meeting-001',
      sourceType: 'meeting',
      title: 'VectorForge Portfolio Review',
      sourceDate: '2026-07-25T15:00:00Z',
      locator: 'demo_data/raw/meetings/vectorforge-2026-07-25.md',
      content: 'The chief financial officer reported recognized annual recurring revenue of 3.4 million USD. The 3.8 million USD CRM value included signed contracts that had not started.',
      verificationStatus: 'direct company statement',
    },
    {
      id: 'crm-activity-002',
      sourceType: 'crm',
      title: 'Revenue correction',
      sourceDate: '2026-07-28T13:30:00Z',
      locator: 'demo_data/raw/crm/activities.json',
      content: 'The chief financial officer reported recognized annual recurring revenue of 3.4 million USD.',
      verificationStatus: 'confirmed',
    },
    {
      id: 'slack-001',
      sourceType: 'slack',
      title: '#portfolio-vectorforge',
      sourceDate: '2026-07-29T13:05:00Z',
      locator: 'thread-vectorforge-july',
      content: 'The chief financial officer confirmed that recognized annual recurring revenue is 3.4 million USD.',
      verificationStatus: 'confirmed',
    },
    {
      id: 'crm-activity-001',
      sourceType: 'crm',
      title: 'Second quarter update',
      sourceDate: '2026-07-11T15:00:00Z',
      locator: 'demo_data/raw/crm/activities.json',
      content: 'The company reported annual recurring revenue of 3.8 million USD. Monthly burn was 420000 USD.',
      verificationStatus: 'superseded',
    },
    {
      id: 'crm-activity-003',
      sourceType: 'crm',
      title: 'Customer expansion',
      sourceDate: '2026-08-06T16:00:00Z',
      locator: 'demo_data/raw/crm/activities.json',
      content: 'Northbank expanded from one production workload to four workloads.',
      verificationStatus: 'confirmed',
    },
    {
      id: 'slack-002',
      sourceType: 'slack',
      title: '#portfolio-vectorforge',
      sourceDate: '2026-08-07T14:20:00Z',
      locator: 'thread-vectorforge-margin',
      content: 'We still need the gross margin effect before the next review.',
      verificationStatus: 'internal note',
    },
    {
      id: 'slack-003',
      sourceType: 'slack',
      title: '#portfolio-vectorforge',
      sourceDate: '2026-08-15T10:15:00Z',
      locator: 'thread-vectorforge-hiring',
      content: 'The company opened four infrastructure engineering roles.',
      verificationStatus: 'public link reviewed',
    },
    {
      id: 'slack-017',
      sourceType: 'slack',
      title: '#portfolio-vectorforge',
      sourceDate: '2026-08-20T15:05:00Z',
      locator: 'thread-vectorforge-funding',
      content: 'The company plans to start a Series B process in January 2027.',
      verificationStatus: 'company statement',
    },
  ],
  coverage: [
    { category: 'CRM', count: 4, latestDate: '2026-08-06T16:00:00Z' },
    { category: 'Meetings', count: 1, latestDate: '2026-07-25T15:00:00Z' },
    { category: 'Slack', count: 4, latestDate: '2026-08-20T15:05:00Z' },
    { category: 'News', count: 2, latestDate: '2026-08-14T09:00:00Z' },
  ],
};
